import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date


def _build_html(state: str, city: str, current: dict, forecast: list[dict]) -> str:
    today_str = date.today().strftime("%B %d, %Y")

    forecast_rows = ""
    if forecast:
        for f in forecast:
            forecast_rows += f"""
            <tr>
                <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;">{f['time']}</td>
                <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;">{f['temp']}°C</td>
                <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;">{f['feels_like']}°C</td>
                <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;">{f['humidity']}%</td>
                <td style="padding:8px 12px;border-bottom:1px solid #e0e0e0;">{f['description']}</td>
            </tr>"""
    else:
        forecast_rows = '<tr><td colspan="5" style="padding:8px 12px;color:#888;">No further forecast data for today.</td></tr>'

    return f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }}
    .container {{ max-width: 620px; margin: 30px auto; background: #fff; border-radius: 10px;
                  box-shadow: 0 2px 8px rgba(0,0,0,0.1); overflow: hidden; }}
    .header {{ background: linear-gradient(135deg, #1a73e8, #0d47a1); color: #fff;
               padding: 28px 32px; }}
    .header h1 {{ margin: 0 0 4px; font-size: 22px; }}
    .header p {{ margin: 0; font-size: 14px; opacity: 0.85; }}
    .section {{ padding: 24px 32px; }}
    .section h2 {{ margin: 0 0 16px; font-size: 16px; color: #1a73e8;
                   border-bottom: 2px solid #e8f0fe; padding-bottom: 8px; }}
    .current-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
    .metric {{ background: #f8f9ff; border-radius: 8px; padding: 14px 16px; }}
    .metric .label {{ font-size: 11px; color: #888; text-transform: uppercase;
                      letter-spacing: 0.5px; margin-bottom: 4px; }}
    .metric .value {{ font-size: 22px; font-weight: bold; color: #1a1a1a; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
    th {{ background: #e8f0fe; color: #1a73e8; text-align: left;
          padding: 10px 12px; font-size: 12px; text-transform: uppercase; }}
    td {{ color: #333; }}
    tr:last-child td {{ border-bottom: none; }}
    .footer {{ background: #f4f6f9; text-align: center; padding: 16px;
               font-size: 12px; color: #999; }}
  </style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Weather Report — {state}</h1>
    <p>Capital: {city} &nbsp;|&nbsp; {today_str}</p>
  </div>

  <div class="section">
    <h2>Current Conditions</h2>
    <div class="current-grid">
      <div class="metric">
        <div class="label">Temperature</div>
        <div class="value">{current['temp']}°C</div>
      </div>
      <div class="metric">
        <div class="label">Feels Like</div>
        <div class="value">{current['feels_like']}°C</div>
      </div>
      <div class="metric">
        <div class="label">Humidity</div>
        <div class="value">{current['humidity']}%</div>
      </div>
      <div class="metric">
        <div class="label">Wind Speed</div>
        <div class="value">{current['wind_speed']} km/h</div>
      </div>
    </div>
    <p style="margin:16px 0 0;color:#555;font-size:15px;">
      <strong>Sky:</strong> {current['description']}
    </p>
  </div>

  <div class="section" style="padding-top:0;">
    <h2>Today's Forecast</h2>
    <table>
      <thead>
        <tr>
          <th>Time</th><th>Temp</th><th>Feels Like</th><th>Humidity</th><th>Condition</th>
        </tr>
      </thead>
      <tbody>
        {forecast_rows}
      </tbody>
    </table>
  </div>

  <div class="footer">
    Data provided by OpenWeatherMap &nbsp;·&nbsp; Generated by India Weather Mailer
  </div>
</div>
</body>
</html>
"""


def send_weather_email(
    state: str,
    city: str,
    current: dict,
    forecast: list[dict],
    smtp_host: str,
    smtp_port: int,
    sender: str,
    password: str,
    recipient: str,
) -> None:
    subject = f"Weather Report: {state} — {date.today().strftime('%B %d, %Y')}"
    html = _build_html(state, city, current, forecast)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())
